[package]
name = "hermes"
version = "0.1.0"
authors = ["Kasun Vithanage <alankasun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
bytes = "0.5.6"
